I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 59, in script
    show screen patreon_button
  File "renpy/common/000statements.rpy", line 647, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
Exception: Screen patreon_button is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 59, in script
    show screen patreon_button
  File "C:\FreeFromDrive\SaveYourDesktop\renpy-8.3.6-sdk\renpy\ast.py", line 1987, in execute
    self.call("execute")
  File "C:\FreeFromDrive\SaveYourDesktop\renpy-8.3.6-sdk\renpy\ast.py", line 1966, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\FreeFromDrive\SaveYourDesktop\renpy-8.3.6-sdk\renpy\statements.py", line 374, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 647, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
  File "C:\FreeFromDrive\SaveYourDesktop\renpy-8.3.6-sdk\renpy\display\screen.py", line 1328, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen patreon_button is not known.


Windows-10-10.0.22631 AMD64
Ren'Py 8.3.6.25022803
DoesNotKommunisere 1.0
Wed May  7 14:51:24 2025
